/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.UI;

import com.mycompany.Entity.Profesor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hecta
 */
public class RegistroPro extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Profesor> profesores = new ArrayList<>();

    /**
     * Creates new form RegistroPro
     */
    public RegistroPro() {
        initComponents();
        this.setTitle("EduTrack");
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("Especialidad");
        readFile();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreProfe = new javax.swing.JTextField();
        DireccionProfe = new javax.swing.JTextField();
        EdadProfe = new javax.swing.JSpinner();
        Especialidad = new javax.swing.JComboBox<>();
        Agregar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaestros = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Ordenamiento = new javax.swing.JComboBox<>();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jLabel3.setText("Dirección");

        jLabel4.setText("Especialidad");

        DireccionProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionProfeActionPerformed(evt);
            }
        });

        Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemáticas", "Física", "Biología", "Química", "Español", "Informática" }));

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        tablaMaestros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMaestros);

        jLabel6.setText("Ordenar por");

        Ordenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Especialidad" }));
        Ordenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NombreProfe)
                                        .addComponent(DireccionProfe, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(EdadProfe, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Agregar)
                        .addGap(47, 47, 47)
                        .addComponent(Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Ordenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EdadProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DireccionProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Borrar)
                    .addComponent(jLabel6)
                    .addComponent(Ordenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DireccionProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionProfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionProfeActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        NombreProfe.setText("");
        EdadProfe.setValue(0);
        DireccionProfe.setText("");
        profesores.remove(profesores.size() - 1);
        refreshTable();
        
        // Escribir archivo
        try {
            FileOutputStream f = new FileOutputStream(new File("myObjects4.txt"));
            ObjectOutputStream o = new ObjectOutputStream(f);
                        
            o.writeObject(profesores);
            o.close();
            f.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"cannot write");
        }
    }//GEN-LAST:event_BorrarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        try {
            Profesor profesor = new Profesor();
            profesor.setName(NombreProfe.getText());
            profesor.setAge(Integer.parseInt(EdadProfe.getValue().toString()));
            profesor.setAddress(DireccionProfe.getText());
            profesor.setEspecialidad(Especialidad.getSelectedItem().toString());
            profesores.add(profesor);
            refreshTable();
            
            // Escribir archivo
            try (FileOutputStream f = new FileOutputStream("myObjects4.txt");
            ObjectOutputStream o = new ObjectOutputStream(f);){
                o.writeObject(profesores);
                o.close();
                f.close();
                
            } catch (FileNotFoundException e) {
                System.out.println("File not found");
                throw new RuntimeException(e);
            } catch (IOException ioe) {
                System.out.println("Error while writing");
            }           
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void OrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenamientoActionPerformed
        // TODO add your handling code here:
        if("Nombre".equals(Ordenamiento.getSelectedItem().toString())) {
            // Expresion lambda para ordenar el arraylist por calificacion
            Collections.sort(profesores, (a1, a2) -> a1.getName().compareTo(a2.getName()));
        } else {
            // Expresion lambda para ordenar por orden alfabetico el arraylist
            Collections.sort(profesores, (a1, a2) -> a1.getEspecialidad().compareTo(a2.getEspecialidad()));
        }
        refreshTable();
    }//GEN-LAST:event_OrdenamientoActionPerformed

    /**
     * Refrescar Tabla
     */
    public void refreshTable() {
        // Borrar todos los elementos del modelo
        while (modelo.getRowCount()> 0) {            
            modelo.removeRow(0);
        }
        
        for (Profesor profesor : profesores) {
            Object a[] = new Object[3];
            a[0] = profesor.getName();
            a[1] = profesor.getAge();
            a[2] = profesor.getEspecialidad();
            modelo.addRow(a);
        }
        tablaMaestros.setModel(modelo);
    }
    
    /**
     * Leer archivo
     */
    public void readFile() {
        try (FileInputStream fi = new FileInputStream(new File("myObjects4.txt"));
            ObjectInputStream oi = new ObjectInputStream(fi);){
            
            profesores = (ArrayList) oi.readObject();
            oi.close();
            fi.close();
            
            for(Profesor profesor : profesores) {
                System.out.println(profesor);
            }
        } catch (Exception e) {
            System.out.println("File not found");
        }
        
        //refreshTable();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Borrar;
    private javax.swing.JTextField DireccionProfe;
    private javax.swing.JSpinner EdadProfe;
    private javax.swing.JComboBox<String> Especialidad;
    private javax.swing.JTextField NombreProfe;
    private javax.swing.JComboBox<String> Ordenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMaestros;
    // End of variables declaration//GEN-END:variables
}
